using Rmms.Domain.Common;
using Rmms.Domain.Enums;

namespace Rmms.Domain.Devices;

/// <summary>
/// Device registration per BR-105 (PG has EXACTLY 1 active device).
///
/// Spec: <c>knowledge-base/04-data-model.md</c> (user_devices) + M02 module spec.
///
/// State transitions (per BR-106):
///   <see cref="DeviceStatus.PendingApproval"/>
///     -- Leader/Admin approve --> <see cref="DeviceStatus.Active"/>
///     -- Leader/Admin reject  --> <see cref="DeviceStatus.Rejected"/>
///   <see cref="DeviceStatus.Active"/>
///     -- another device approved for same user --> <see cref="DeviceStatus.Replaced"/>
///
/// Sprint 01 ships <c>PendingApproval</c>+<c>Active</c> states; full approval workflow
/// (notification + Leader/Admin UI + Approve/Reject endpoints) lands in Sprint 02.
/// </summary>
public sealed class UserDevice : AuditableEntity, IAggregateRoot
{
    public Guid UserId { get; private set; }

    /// <summary>Stable per-install identifier generated by mobile app (UUID v4).</summary>
    public string DeviceId { get; private set; } = string.Empty;

    public string DeviceName { get; private set; } = string.Empty;

    /// <summary><c>ios</c> or <c>android</c>.</summary>
    public string Os { get; private set; } = string.Empty;
    public string OsVersion { get; private set; } = string.Empty;
    public string AppVersion { get; private set; } = string.Empty;

    /// <summary>Firebase Cloud Messaging token — nullable until app registers it.</summary>
    public string? FcmToken { get; private set; }

    public DeviceStatus Status { get; private set; }

    public Guid? ApprovedBy { get; private set; }
    public DateTimeOffset? ApprovedAt { get; private set; }

    public DateTimeOffset? LastUsedAt { get; private set; }

    private UserDevice() { }

    /// <summary>
    /// Factory: first device for a user — auto-approved (no other active device to compare against).
    /// Use during initial registration / when no active device exists for this user.
    /// </summary>
    public static UserDevice RegisterFirstActive(Guid userId, string deviceId, string deviceName, string os, string osVersion, string appVersion, string? fcmToken, DateTimeOffset at)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(deviceId);
        ArgumentException.ThrowIfNullOrWhiteSpace(deviceName);

        return new UserDevice
        {
            UserId = userId,
            DeviceId = deviceId.Trim(),
            DeviceName = deviceName.Trim(),
            Os = NormalizeOs(os),
            OsVersion = (osVersion ?? string.Empty).Trim(),
            AppVersion = (appVersion ?? string.Empty).Trim(),
            FcmToken = string.IsNullOrWhiteSpace(fcmToken) ? null : fcmToken.Trim(),
            Status = DeviceStatus.Active,
            ApprovedAt = at,
            LastUsedAt = at,
        };
    }

    /// <summary>
    /// Factory: subsequent device — needs Leader/Admin approval (BR-106).
    /// Created when user already has an active device and is logging in from a different one.
    /// </summary>
    public static UserDevice RegisterPendingApproval(Guid userId, string deviceId, string deviceName, string os, string osVersion, string appVersion, string? fcmToken)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(deviceId);
        ArgumentException.ThrowIfNullOrWhiteSpace(deviceName);

        return new UserDevice
        {
            UserId = userId,
            DeviceId = deviceId.Trim(),
            DeviceName = deviceName.Trim(),
            Os = NormalizeOs(os),
            OsVersion = (osVersion ?? string.Empty).Trim(),
            AppVersion = (appVersion ?? string.Empty).Trim(),
            FcmToken = string.IsNullOrWhiteSpace(fcmToken) ? null : fcmToken.Trim(),
            Status = DeviceStatus.PendingApproval,
        };
    }

    // ----- Domain methods (Sprint 02 will wire approval UI to these) -----

    public void Approve(Guid approverUserId, DateTimeOffset at)
    {
        if (Status != DeviceStatus.PendingApproval)
        {
            throw new InvalidOperationException(
                $"Cannot approve a device that is {Status}. Only PendingApproval is approvable.");
        }
        Status = DeviceStatus.Active;
        ApprovedBy = approverUserId;
        ApprovedAt = at;
        LastUsedAt = at;
    }

    public void Reject(Guid approverUserId, DateTimeOffset at)
    {
        if (Status != DeviceStatus.PendingApproval)
        {
            throw new InvalidOperationException(
                $"Cannot reject a device that is {Status}. Only PendingApproval is rejectable.");
        }
        Status = DeviceStatus.Rejected;
        ApprovedBy = approverUserId;
        ApprovedAt = at;
    }

    /// <summary>Called when a new device for this user becomes active — old device must be replaced.</summary>
    public void MarkReplaced()
    {
        if (Status != DeviceStatus.Active)
        {
            throw new InvalidOperationException(
                $"Cannot mark a {Status} device as Replaced. Only Active devices can be replaced.");
        }
        Status = DeviceStatus.Replaced;
    }

    public void Touch(DateTimeOffset at)
    {
        LastUsedAt = at;
    }

    public void UpdateFcmToken(string? fcmToken)
    {
        FcmToken = string.IsNullOrWhiteSpace(fcmToken) ? null : fcmToken.Trim();
    }

    // ----- Helpers -----

    private static string NormalizeOs(string os)
    {
        var normalized = (os ?? string.Empty).Trim().ToLowerInvariant();
        return normalized is "ios" or "android" ? normalized : "android";
    }
}
